/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare function extractCandidateTriplesNapi(text: string, opts?: NapiOptions | undefined | null): Array<NapiTripleCandidate>

export interface NapiOptions {
  aliases?: Record<string, string>
  minConfidence?: number
  ontology?: Record<string, string>
}

export interface NapiTripleCandidate {
  subject: string
  relation: string
  object: string
  confidence: number
  span: Array<number>
  rule: string
}
