/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * One fact as the whole passage states it, with every supporting span.
 * Ordered by first span, so two facts about the same pair can be read in the
 * order the story states them.
 */
export declare function extractAggregatesNapi(text: string, opts?: NapiOptions | undefined | null): Array<NapiAggregateTriple>

export declare function extractCandidateTriplesNapi(text: string, opts?: NapiOptions | undefined | null): Array<NapiTripleCandidate>

export interface NapiAggregateTriple {
  subject: string
  relation: string
  object: string
  confidence: number
  spans: Array<Array<number>>
  rules: Array<string>
}

export interface NapiOptions {
  aliases?: Record<string, string>
  minConfidence?: number
  rejections?: Array<NapiRejection>
  ontology?: Record<string, string>
}

export interface NapiRejection {
  subject: string
  relation: string
  object: string
}

export interface NapiTripleCandidate {
  subject: string
  relation: string
  object: string
  confidence: number
  span: Array<number>
  rule: string
}
