// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Polarity } from "./Polarity";

/**
 * One fact as a whole document states it, with every piece of evidence for it.
 *
 * `TripleCandidate` is per-sentence and `extract_candidate_triples` keeps the
 * highest-confidence one per triple, discarding the spans of the rest. An
 * aggregate keeps them: a passage stating one fact three ways yields one
 * aggregate carrying three spans.
 */
export type AggregateTriple = { subject: string, relation: string, object: string, 
/**
 * Whether the document states this fact or denies it. A denial and the
 * assertion of the same triple are two aggregates, not one, because they
 * are two claims — and a document carrying both is the contradiction
 * `find_conflicts` reports.
 */
polarity: Polarity, 
/**
 * The highest confidence of any supporting candidate.
 *
 * IMPORTANT: repetition does not raise it, and `spans.len()` is the only
 * thing that reports corroboration. In fiction a restatement is not
 * independent evidence — an unreliable narrator restates a falsehood as
 * readily as a reliable one states a fact — so summing would let a
 * thrice-repeated lie outrank a once-stated fact, and averaging would
 * punish a strong statement for being echoed by a weaker phrasing. The
 * score answers "how good is the best evidence", not "how much is there".
 */
confidence: number, 
/**
 * Every span the fact was found at, in document order. Never empty.
 */
spans: Array<[number, number]>, 
/**
 * The rules that produced those spans, first occurrence first, without
 * repeats. Two spans from one rule name it once.
 */
rules: Array<string>, };
