// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AggregateTriple } from "./AggregateTriple";
import type { ConflictKind } from "./ConflictKind";

/**
 * Two claims a single passage cannot both support, with the evidence for each.
 *
 * IMPORTANT: a conflict is not a ranking. Neither side is the true one, and
 * the crate has no way to decide which is: both carry their spans so the
 * decision stays with whoever can read the manuscript.
 */
export type Conflict = { kind: ConflictKind, 
/**
 * The claim appearing first in the document.
 */
left: AggregateTriple, 
/**
 * The claim appearing second.
 */
right: AggregateTriple, };
