// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why two aggregates cannot both be true.
 */
export type ConflictKind = "denial" | "cardinality";
