// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rejection } from "./Rejection";

/**
 * Configuration for entity and relation extraction.
 */
export type Options = { 
/**
 * Optional mapping from surface forms to canonical entity names.
 * Example: { "Marcus": "marcus_hale", "Mr Marcus Hale": "marcus_hale" }
 * All mentions matching a key in this map resolve to the value.
 *
 * IMPORTANT: the key's own shape selects how it matches. A key carrying an
 * uppercase character is matched against the mention's surface form
 * exactly, which is the capitalized run with `.` dropped as a separator:
 * "Mr Marcus Hale", never "Mr. Marcus Hale". A wholly lowercase key is a
 * lexicon entry instead: the phrase is searched for in the text as a
 * literal, word-bounded, case-insensitive match and becomes a mention of
 * the canonical name there, which is how "the detective" reaches a
 * referent no capitalized-run detector can see. A lexicon match that
 * overlaps a mention already detected is dropped, so a key can add a
 * mention but never replace one. A pronoun can take a lexicon mention as
 * its referent, and a pronoun the mention covers is replaced by it.
 */
aliases: { [key in string]: string }, 
/**
 * Minimum confidence threshold for returned candidates.
 * Candidates below this score are filtered out.
 * Default: 0.0 (all candidates returned).
 */
min_confidence: number | null, 
/**
 * Candidates the caller has already judged wrong. A candidate whose
 * (subject, relation, object) matches one of these is not emitted.
 *
 * IMPORTANT: the crate persists nothing. This set is caller-owned state
 * handed in per call, so where it is stored between runs, and for how
 * long, stays the caller's decision.
 *
 * A rejection suppresses and does nothing else: it does not lower the
 * confidence of a sibling candidate, and it does not weaken the rule that
 * produced it. Feeding rejections back into scoring would make the output
 * depend on a history the caller cannot see in the result, and the span
 * and rule name are on every candidate precisely so a caller can audit
 * why it fired.
 */
rejections: Array<Rejection>, 
/**
 * Optional mapping from recognized relation patterns to a caller-supplied controlled vocabulary.
 * Example: { "loves": "romantic_interest", "is_married_to": "spouse" }
 * If a relation type is not in this map, the heuristic default is used.
 */
ontology: { [key in string]: string }, };
