// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for entity and relation extraction.
 */
export type Options = { 
/**
 * Optional mapping from surface forms to canonical entity names.
 * Example: { "the detective": "marcus", "ms. chen": "chen" }
 * All mentions matching a key in this map resolve to the value.
 */
aliases: { [key in string]: string }, 
/**
 * Minimum confidence threshold for returned candidates.
 * Candidates below this score are filtered out.
 * Default: 0.0 (all candidates returned).
 */
min_confidence: number | null, 
/**
 * Optional mapping from recognized relation patterns to a caller-supplied controlled vocabulary.
 * Example: { "loves": "romantic_interest", "is_married_to": "spouse" }
 * If a relation type is not in this map, the heuristic default is used.
 */
ontology: { [key in string]: string }, };
