// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for entity and relation extraction.
 */
export type Options = { 
/**
 * Optional mapping from surface forms to canonical entity names.
 * Example: { "Marcus": "marcus_hale", "Mr Marcus Hale": "marcus_hale" }
 * All mentions matching a key in this map resolve to the value.
 *
 * IMPORTANT: the key's own shape selects how it matches. A key carrying an
 * uppercase character is matched against the mention's surface form
 * exactly, which is the capitalized run with `.` dropped as a separator:
 * "Mr Marcus Hale", never "Mr. Marcus Hale". A wholly lowercase key is a
 * lexicon entry instead: the phrase is searched for in the text as a
 * literal, word-bounded, case-insensitive match and becomes a mention of
 * the canonical name there, which is how "the detective" reaches a
 * referent no capitalized-run detector can see. A lexicon match that
 * overlaps a mention already detected is dropped, so a key can add a
 * mention but never replace one.
 */
aliases: { [key in string]: string }, 
/**
 * Minimum confidence threshold for returned candidates.
 * Candidates below this score are filtered out.
 * Default: 0.0 (all candidates returned).
 */
min_confidence: number | null, 
/**
 * Optional mapping from recognized relation patterns to a caller-supplied controlled vocabulary.
 * Example: { "loves": "romantic_interest", "is_married_to": "spouse" }
 * If a relation type is not in this map, the heuristic default is used.
 */
ontology: { [key in string]: string }, };
