// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a document states a fact or states that it does not hold.
 *
 * IMPORTANT: a denial is a claim, not a missing assertion. Text that neither
 * asserts nor denies — a conditional, a modal, a question, a complement held
 * open by its main verb — produces no aggregate at all and so has no polarity.
 */
export type Polarity = "asserted" | "denied";
