// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A candidate the caller has judged wrong, named by the triple it emitted.
 *
 * IMPORTANT: the three fields are the *normalized* values as they appeared on
 * the `TripleCandidate`, which for `relation` means after any `ontology`
 * mapping. What the caller saw is what the caller rejects; nothing here is
 * re-derived from the source text.
 *
 * Keying on the triple rather than the span is deliberate. A span does not
 * survive an edit to the manuscript, so a span-keyed rejection would come back
 * on the next save; a triple survives every edit that does not restate the
 * fact. The cost is that the rejection is document-wide: a caller who meant
 * "not in this passage" suppresses the claim everywhere, which is the blunter
 * and more inspectable of the two errors.
 */
export type Rejection = { subject: string, relation: string, object: string, };
