// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TripleCandidate } from "./TripleCandidate";

/**
 * A reference span into the input text with its corresponding surface text.
 */
export type SpannedTriple = { candidate: TripleCandidate, 
/**
 * The actual text from input[span[0]..span[1]].
 */
text: string, };
