// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A candidate relational fact extracted from text.
 * Every candidate carries confidence, provenance span, and the rule that produced it.
 */
export type TripleCandidate = { 
/**
 * The subject entity (normalized to lowercase with underscores for multi-word entities).
 */
subject: string, 
/**
 * The relation type (normalized from verb phrases to a controlled vocabulary).
 */
relation: string, 
/**
 * The object entity (normalized to lowercase with underscores for multi-word entities).
 */
object: string, 
/**
 * Confidence score from 0.0 to 1.0, derived from rule strength and entity proximity.
 */
confidence: number, 
/**
 * Byte range [start, end) in the input text where this candidate was extracted.
 */
span: [number, number], 
/**
 * The name of the extraction rule that produced this candidate.
 * Examples: "possessive-sister-pattern", "verb-mentor-pattern".
 */
rule: string, };
